# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20160410_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='line_item_total',
            field=models.DecimalField(decimal_places=2, default=12.99, max_digits=10),
            preserve_default=False,
        ),
    ]
